/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import { useLayoutEffect, useRef } from 'react'
import { useGLTF, CubeCamera } from '@react-three/drei'

export default function Escena({ ...props }) {
    const group = useRef()
    const { nodes, materials } = useGLTF('/escena.glb')
    console.log({nodes,materials})
    // const snap = useSnapshot(state);


    // useLayoutEffect(() => {
    //     materials.Silla.color.set('#00000')
    //   }, [materials])
    return (
        <group ref={group} {...props} dispose={null}>
            <group ref={group} {...props} dispose={null}>
                <mesh 
                    geometry={nodes.escena.geometry} material={materials.madera} position={[-7.966238, -0.10155, -7.966238]} scale={0.5}/> 
            </group>
        </group>
    )
}

useGLTF.preload('/escena.glb')
