/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import { useLayoutEffect, useRef } from 'react'
import { useGLTF, CubeCamera } from '@react-three/drei'

export default function Prueba({ ...props }) {
    const group = useRef()
    const { nodes, materials } = useGLTF('/prueba.glb')
    // const snap = useSnapshot(state);
    return (
        <group ref={group} {...props} dispose={null}>
            <group ref={group} {...props} dispose={null}>
                <mesh geometry={nodes.mono.geometry} material={materials.material1} />
                <mesh geometry={nodes.cubo.geometry} material={materials.material2} />
            </group>
        </group>
    )
}

useGLTF.preload('/prueba.glb')
